language: ruby
rvm:
  - 2.4.1
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE wakatime_test'
  - mysql -e 'CREATE DATABASE wakatime_development'
  - mysql -e 'CREATE DATABASE wakatime_production'
script:
  - RAILS_ENV=development rake db:migrate
